apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-appapi-harp
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      app: appapi-harp
  template:
    metadata:
      labels:
        app: appapi-harp
    spec:
      containers:
      - name: harp
        image: ghcr.io/nextcloud/nextcloud-appapi-harp:release
        env:
        - name: HP_SHARED_KEY
          value: "JI0mXuyI3iCX5Hu86jf5" # Você definirá isso no Nextcloud depois
        - name: NC_INSTANCE_URL
          value: "https://nextcloud-tailscale-nextcloud-ingress-ingress.tailf76cf8.ts.net"
        ports:
        - containerPort: 8780
        - containerPort: 8782

